# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Ole Kristian Mørch-Storstein"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Engineer. Developer. Dad. Robot rights activist and occasional vampire hunter.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://okms.github.io"
twitter_username: okmsPrime
github_username:  okms

# Build settings
#theme: "minima"
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
# minimal_mistakes_skin: "neon"
name: "Ole Kristian Mørch-Storstein"
site.description: "Technical blog for Ole Kristian Mørch-Storstein, focusing on Microsoft 365, SharePoint and web development"
repository: "okms/okms.github.com"

permalink: /:year/:month/:title:output_ext
# header:
#   teaser: "/assets/img/teaser.jpg"
# logo: "/assets/img/88x88.png"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      words_per_minute: 140
      comments: true
      share: true
      related: true
    # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

twitter:
  username: "okmsPrime"

og_image: /assets/img/okms-avatar.jpg

social:
  type:  Person
  name:  "Ole Kristian Mørch-Storstein"
  links:
    - "https://twitter.com/okmsPrime"
    - "https://www.facebook.com/okstor"
    - "https://instagram.com/okstor"
    - "https://www.linkedin.com/in/olekms"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-185476802-1"
    anonymize_ip: false # default

author:
  name     : "Ole Kristian Mørch-Storstein"
  avatar   : "/assets/img/okms-avatar.jpg"
  bio      : "Engineer. Developer. Dad. Robot rights activist and occasional vampire hunter. CTO @ [Puzzlepart](https://puzzlepart.com)"
  location : "Oslo, Norway"


footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/okmsPrime"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/okms"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/okstor"

timezone: Europe/Oslo

plugins:
  - jekyll-feed
  - jekyll-include-cache

include: ["_pages"]

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
